# Generated by Django 5.2.7 on 2025-11-18 16:44

import django.db.models.deletion
import phonenumber_field.modelfields
import utils.models.validation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Home for example.', max_length=55, verbose_name='title')),
                ('recipient_full_name', models.CharField(blank=True, help_text='Defaults to user fullname if left blank.', max_length=128, verbose_name='recipient full name')),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Defaults to user phone number if left blank.', max_length=128, region='IR', verbose_name='recipient phone number')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='additional address info')),
                ('building_number', models.PositiveSmallIntegerField(verbose_name='building number')),
                ('unit_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='unit number')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('is_default', models.BooleanField(default=False, verbose_name='default address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_addresses', to='locations.city', verbose_name='city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_addresses', to='locations.province', verbose_name='province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ('-is_default', 'id'),
                'unique_together': {('user', 'postal_code'), ('user', 'title')},
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
    ]
