# Generated by Django 5.2.7 on 2025-11-23 06:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='recipient_full_name',
            field=models.CharField(blank=True, help_text="Defaults to user's full name if left blank.", max_length=128, verbose_name='recipient full name'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='recipient_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Defaults to user's phone number if left blank.", max_length=128, region='IR', verbose_name='recipient phone number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='title',
            field=models.CharField(help_text='Example: Home, Work, Office.', max_length=55, verbose_name='title'),
        ),
    ]
