# Generated by Django 5.2.7 on 2025-11-11 13:00

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='request ID')),
                ('purpose', models.CharField(blank=True, max_length=128, null=True, verbose_name='purpose')),
                ('hashed_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='hashed token')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='requested at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='attempt count')),
                ('next_request_at', models.DateTimeField(blank=True, null=True, verbose_name='next request at')),
                ('throttle_until', models.DateTimeField(blank=True, null=True, verbose_name='throttle until')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTPGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('purpose', models.CharField(max_length=255, verbose_name='purpose')),
                ('consumed', models.BooleanField(default=False, verbose_name='consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='request ID')),
                ('purpose', models.CharField(blank=True, max_length=128, null=True, verbose_name='purpose')),
                ('hashed_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='hashed token')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='requested at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='attempt count')),
                ('next_request_at', models.DateTimeField(blank=True, null=True, verbose_name='next request at')),
                ('throttle_until', models.DateTimeField(blank=True, null=True, verbose_name='throttle until')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IR', verbose_name='phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
