from django.conf import settings

DEFAULTS = {
    "TOKEN_LENGTH": 6,
    "TOKEN_LIFETIME_SECONDS": 180,
    "REQUEST_COOLDOWN_SECONDS": 180,
    "MAX_ATTEMPTS": 3,
    "THROTTLE_SECONDS": 300,
    "TEMPORARY_PERMISSIONS_LIFETIME_SECONDS": 300,
}

USER_CONF = getattr(settings, "VERIFICATION", {})

# Merge defaults with user overrides
CONF = {**DEFAULTS, **USER_CONF}

# Export constants for convenience
TOKEN_LENGTH = CONF["TOKEN_LENGTH"]
TOKEN_LIFETIME_SECONDS = CONF["TOKEN_LIFETIME_SECONDS"]
REQUEST_COOLDOWN_SECONDS = CONF["REQUEST_COOLDOWN_SECONDS"]
MAX_ATTEMPTS = CONF["MAX_ATTEMPTS"]
THROTTLE_SECONDS = CONF["THROTTLE_SECONDS"]
TEMPORARY_PERMISSIONS_LIFETIME_SECONDS = CONF["TEMPORARY_PERMISSIONS_LIFETIME_SECONDS"]