# Generated by Django 5.2.7 on 2025-11-23 06:21

import django.db.models.deletion
import django.db.models.functions.text
import mptt.fields
import utils.models.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Human-readable name for this attribute (e.g., 'Color', 'Storage', 'Brand').", max_length=128, unique=True, verbose_name='title')),
                ('scope', models.CharField(choices=[('product', 'Product'), ('sku', 'SKU')], help_text='Defines whether this attribute applies to the product as a whole or to its variants. Product-level attributes are shared by all variants (e.g., Brand, CPU, Screen Size). Variant-level attributes can differ between variants (e.g., Color, Size, Storage).', max_length=10, verbose_name='scope')),
                ('filterable', models.BooleanField(default=False, help_text='If enabled, this attribute will appear as a filter option in product listings and search pages. Use this for attributes that customers typically use to narrow down results (e.g., Color, Size, Brand). Attributes that are only descriptive (e.g., Model Number, Material Composition) should usually not be filterable.', verbose_name='filterable')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['title'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='value')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productattribute', verbose_name='product attribute')),
            ],
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, limit_choices_to=models.Q(('level__lt', 2)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', unique=True, verbose_name='slug')),
                ('title', models.CharField(help_text='The human-readable name of the product.', max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Optional long-form description displayed on the product page.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the storefront.', verbose_name='is active')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productbrand', verbose_name='product brand')),
                ('product_category', models.ForeignKey(help_text='The hierarchical category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='product category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Unique stock keeping unit identifier for inventory tracking.', max_length=50, unique=True, verbose_name='SKU')),
                ('title', models.CharField(blank=True, help_text="Optional SKU-specific title (e.g., '128GB Blue').", max_length=255, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this SKU is visible and available for sale.', verbose_name='is active')),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this as the main SKU of the product.', verbose_name='is primary')),
                ('product', models.ForeignKey(help_text='The product this SKU belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product SKU',
                'verbose_name_plural': 'product SKUs',
                'ordering': ['product', 'sku'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO.', max_length=255, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the main display image for this SKU', verbose_name='is primary')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.', verbose_name='display order')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productsku', verbose_name='SKU')),
            ],
            options={
                'ordering': ['position'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='reserved')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.productsku', verbose_name='SKU')),
            ],
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="A descriptive name for this product type (e.g., 'Smartphone', 'Laptop').", max_length=100, unique=True, verbose_name='title')),
                ('has_variants', models.BooleanField(default=False, help_text='Indicates whether products of this type can have multiple variants. If enabled, products under this type can define variant-specific attributes (e.g., color, size, storage) and each variant can have its own SKU, price, and stock. If disabled, products of this type are treated as single, non-variant items.', verbose_name='has variants')),
                ('product_category', models.ForeignKey(help_text='Select the main category this product type belongs to. Products of this type will usually appear under this category, and its attributes will be used to build filters for products within it.', on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='products.productcategory', verbose_name='product category')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ['title'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(help_text='Defines the type of product, determining allowed attributes and whether it can have variants.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype', verbose_name='product type'),
        ),
        migrations.CreateModel(
            name='ProductTypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, help_text="If enabled, this attribute must have a value for every product or variant of this type. Leave unchecked for optional attributes. For example, 'Storage Size' might be required for all smartphone variants, while 'Color' might be optional.", verbose_name='required')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_attributes', to='products.productattribute', verbose_name='product attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_attributes', to='products.producttype', verbose_name='product type')),
            ],
            options={
                'verbose_name': 'Type Attribute',
                'verbose_name_plural': 'Type Attributes',
                'ordering': ['product_type__title', 'product_attribute__title'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductSKUAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='product')),
                ('product_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.productsku', verbose_name='SKU')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productattributeoption', verbose_name='attribute option')),
                ('product_type_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producttypeattribute', verbose_name='type attribute')),
            ],
            options={
                'verbose_name': 'product or SKU attribute value',
                'verbose_name_plural': 'product and SKU attribute values',
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='productattributeoption',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('value'), models.F('product_attribute'), name='unique_attr_value_ci'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('level__lte', 2)), name='category_level_less_than_equal_2'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.UniqueConstraint(fields=('product', 'title'), name='unique_sku_title_per_product'),
        ),
        migrations.AddConstraint(
            model_name='producttypeattribute',
            constraint=models.UniqueConstraint(fields=('product_type', 'product_attribute'), name='unique_type_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productskuattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'product_sku', 'product_type_attribute'), name='unique_product_sku_type_attribute'),
        ),
    ]
