# Generated by Django 5.2.7 on 2025-10-10 14:44

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='parent'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('level__lte', 3)), name='category_depth_less_than_equal_3'),
        ),
    ]
