# Generated by Django 5.2.7 on 2025-10-10 15:35

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='category_depth_less_than_equal_3',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, limit_choices_to=models.Q(('level__lt', 2)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='parent'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('level__lte', 2)), name='category_depth_less_than_equal_3'),
        ),
    ]
