# Generated by Django 5.2.7 on 2025-10-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productcategory_category_depth_less_than_equal_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Human-readable name for this attribute (e.g., 'Color', 'Storage', 'Brand').", max_length=128, unique=True, verbose_name='title')),
                ('scope', models.CharField(choices=[('product', 'Product'), ('variant', 'Variant')], help_text='Defines whether this attribute applies to the product as a whole or to its variants. Product-level attributes are shared by all variants (e.g., Brand, CPU, Screen Size). Variant-level attributes can differ between variants (e.g., Color, Size, Storage).', max_length=10, verbose_name='scope')),
                ('filterable', models.BooleanField(default=False, help_text='If enabled, this attribute will appear as a filter option in product listings and search pages. Use this for attributes that customers typically use to narrow down results (e.g., Color, Size, Brand). Attributes that are only descriptive (e.g., Model Number, Material Composition) should usually not be filterable.', verbose_name='filterable')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="A descriptive name for this product type (e.g., 'Smartphone', 'Laptop').", max_length=100, unique=True, verbose_name='title')),
                ('has_variants', models.BooleanField(default=False, help_text='Indicates whether products of this type can have multiple variants. If enabled, products under this type can define variant-specific attributes (e.g., color, size, storage) and each variant can have its own SKU, price, and stock. If disabled, products of this type are treated as single, non-variant items.', verbose_name='has variants')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, help_text="If enabled, this attribute must have a value for every product or variant of this type. Leave unchecked for optional attributes. For example, a 'Storage Size' attribute might be required for all smartphone variants, while 'Color' might be optional.", verbose_name='required')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_attributes', to='products.productattribute', verbose_name='product attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_attributes', to='products.producttype', verbose_name='product type')),
            ],
            options={
                'verbose_name': 'Type Attribute',
                'verbose_name_plural': 'Type Attributes',
                'unique_together': {('product_type', 'product_attribute')},
            },
        ),
    ]
