# Generated by Django 5.2.7 on 2025-10-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattribute_producttype_producttypeattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='value')),
            ],
        ),
        migrations.AlterModelOptions(
            name='producttypeattribute',
            options={'ordering': ['product_type__title', 'product_attribute__title'], 'verbose_name': 'Type Attribute', 'verbose_name_plural': 'Type Attributes'},
        ),
        migrations.AlterUniqueTogether(
            name='producttypeattribute',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='required',
            field=models.BooleanField(default=False, help_text="If enabled, this attribute must have a value for every product or variant of this type. Leave unchecked for optional attributes. For example, 'Storage Size' might be required for all smartphone variants, while 'Color' might be optional.", verbose_name='required'),
        ),
        migrations.AddConstraint(
            model_name='producttypeattribute',
            constraint=models.UniqueConstraint(fields=('product_type', 'product_attribute'), name='unique_type_attribute'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productattribute', verbose_name='product attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributeoption',
            unique_together={('product_attribute', 'value')},
        ),
    ]
