# Generated by Django 5.2.7 on 2025-10-14 14:14

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattributeoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The human-readable name of the product.', max_length=255, unique=True, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', max_length=255, unique=True, verbose_name='slug')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Set a base price only if this product has no variants. For products with variants, leave this blank — each variant will define its own price.', max_digits=10, null=True, verbose_name='price')),
                ('description', models.TextField(blank=True, help_text='Optional long-form description displayed on the product page.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the storefront.', verbose_name='is active')),
                ('product_category', mptt.fields.TreeForeignKey(help_text='The hierarchical category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='product category')),
                ('product_type', models.ForeignKey(help_text='Defines the type of product, determining allowed attributes and whether it can have variants.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype', verbose_name='product type')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
    ]
