# Generated by Django 5.2.7 on 2025-10-15 08:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributeoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit — required for products without variants. Leave blank if this product has variants; each variant will define its own SKU.', max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddConstraint(
            model_name='productattributeoption',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('value'), models.F('product_attribute'), name='unique_attr_value_ci'),
        ),
    ]
