# Generated by Django 5.2.7 on 2025-10-15 09:20

import django.db.models.deletion
import utils.models.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productattributeoption_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Unique stock keeping unit identifier for inventory tracking.', max_length=50, unique=True, verbose_name='SKU')),
                ('title', models.CharField(blank=True, help_text="Optional variant-specific title (e.g., '128GB Blue').", max_length=255, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variant is visible and available for sale.', verbose_name='is active')),
                ('product', models.ForeignKey(help_text='The product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['product', 'sku'],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
    ]
