# Generated by Django 5.2.7 on 2025-10-16 06:57

import django.db.models.deletion
import utils.models.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKUAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'product or variant attribute value',
                'verbose_name_plural': 'product and variant attribute values',
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'title'), name='unique_variant_title_per_product'),
        ),
        migrations.AddField(
            model_name='productskuattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productskuattributevalue',
            name='product_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttypeattribute', verbose_name='type attribute'),
        ),
        migrations.AddField(
            model_name='productskuattributevalue',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.productvariant', verbose_name='variant'),
        ),
        migrations.AddField(
            model_name='productskuattributevalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattributeoption', verbose_name='attribute option'),
        ),
        migrations.AddConstraint(
            model_name='productskuattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'product_variant', 'product_type_attribute'), name='unique_product_variant_type_attribute'),
        ),
    ]
