# Generated by Django 5.2.7 on 2025-10-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productskuattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(help_text='The hierarchical category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='product category'),
        ),
    ]
