# Generated by Django 5.2.7 on 2025-10-20 06:39

import django.db.models.deletion
import utils.models.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO.', max_length=255, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the main display image for this product or variant.', verbose_name='is primary')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.', verbose_name='display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Optional. Attach this image to a specific variant (e.g., color photo).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'product_variant'), name='unique_primary_image_per_product_or_product_variant')],
            },
            bases=(utils.models.validation.ModelValidationMixin, models.Model),
        ),
    ]
