# Generated by Django 5.2.7 on 2025-10-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='reserved')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Optional. Leave empty for products without variants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.productvariant', verbose_name='variant / SKU')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'product_variant'), name='unique_stock_per_product_or_variant')],
            },
        ),
    ]
