# Generated by Django 5.2.7 on 2025-10-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='ProductStock',
        ),
    ]
