# Generated by Django 5.2.7 on 2025-10-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_stock_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='is primary'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'is_primary'), name='unique_variant_is_primary_per_product'),
        ),
    ]
