# Generated by Django 5.2.7 on 2025-10-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariant_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marks this as the main variant of the product.', verbose_name='is primary'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product'),
        ),
    ]
