# Generated by Django 5.2.7 on 2025-10-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productvariant_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product_or_product_variant',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_is_primary_per_product',
        ),
    ]
