# Generated by Django 5.2.7 on 2025-10-27 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_productimage_unique_primary_image_per_product_or_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_category',
            field=models.ForeignKey(default=13, help_text='Select the main category this product type belongs to. Products of this type will usually appear under this category, and its attributes will be used to build filters for products within it.', on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='products.productcategory', verbose_name='product category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='The product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product'),
        ),
    ]
