# Generated by Django 5.2.7 on 2025-10-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productskuattributevalue',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattributeoption', verbose_name='attribute option'),
        ),
    ]
