# Generated by Django 5.2.7 on 2025-11-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productskuattributevalue_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='category_depth_less_than_equal_3',
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('level__lte', 2)), name='category_level_less_than_equal_2'),
        ),
    ]
