# Generated by Django 5.2.7 on 2025-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_productcategory_category_depth_less_than_equal_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Unique identifier used in URLs. Auto-generated from title if left blank.', unique=True, verbose_name='slug'),
        ),
    ]
