# Generated by Django 5.2.7 on 2025-11-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_slug_alter_productbrand_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productskuattributevalue',
            name='product_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producttypeattribute', verbose_name='type attribute'),
        ),
        migrations.AlterField(
            model_name='productskuattributevalue',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productattributeoption', verbose_name='attribute option'),
        ),
    ]
